fetch: PDO::FETCH_OBJ
default: sqlite
connections:
 mysql:
   driver: mysql
   host: localhost
   databse:
   username:
   password:
   charset:
   collation:
   prefix:
   strict: false
 sqlite:
    driver: sqlite
    database: :memory:
    prefix:
